stages:
  - deploy

deploy_job:
  stage: deploy
  only:
    - master

  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run build
    - rsync -avz ./dist/* /www/wwwroot/big-screen.jn.freelinux.cn
